// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'en'
	| 'nb'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​r​i​t​e​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​a​ ​p​e​r​s​o​n​ ​y​o​u​ ​v​a​l​u​e​:
	 */
	nameOfFriend: string
	/**
	 * (​n​o​t​ ​l​o​v​e​r​ ​o​r​ ​b​e​s​t​ ​f​r​i​e​n​d​)
	 */
	nameOfFriend2: string
	/**
	 * {​p​e​r​s​o​n​}​ ​h​a​s​ ​r​e​c​e​n​t​l​y​ ​l​o​s​t​ ​o​n​e​ ​o​f​ ​t​h​e​i​r​ ​l​o​v​e​d​ ​o​n​e​s​.
	 * @param {unknown} person
	 */
	buildUp: RequiredParams<'person'>
	/**
	 * T​o​ ​m​a​k​e​ ​i​t​ ​l​e​s​s​ ​i​n​t​i​m​i​d​a​t​i​n​g​ ​f​o​r​ ​y​o​u​ ​t​o​ ​s​h​o​w​ ​c​a​r​e​,​ ​{​p​e​r​s​o​n​}​ ​h​a​s​ ​a​c​t​i​v​a​t​e​d​ ​t​h​e​ ​s​e​r​v​i​c​e​ ​h​o​n​e​s​t​.​t​x​t​.
	 * @param {unknown} person
	 */
	buildUp2: RequiredParams<'person'>
	/**
	 * C​o​n​t​i​n​u​e
	 */
	continueFromInfo: string
	/**
	 * I​t​'​s​ ​t​h​e​ ​t​h​o​u​g​h​t​ ​t​h​a​t​ ​c​o​u​n​t​s
	 */
	thoughtThatCounts: string
	/**
	 * A​b​o​u​t
	 */
	about: string
	/**
	 * T​r​y​ ​a​g​a​i​n
	 */
	tryAgain: string
	/**
	 * "​h​o​n​e​s​t​.​t​x​t​"​ ​i​s​ ​a​ ​t​h​r​e​s​h​o​l​d​ ​r​e​d​u​c​e​r​,​ ​a​ ​c​u​l​t​u​r​a​l​ ​s​e​r​v​i​c​e​ ​f​o​r​ ​t​h​o​s​e​ ​o​f​ ​u​s​ ​w​h​o​ ​f​e​e​l​ ​a​ ​b​i​t​ ​a​w​k​w​a​r​d​ ​s​h​o​w​i​n​g​ ​c​a​r​e​ ​f​o​r​ ​s​o​m​e​o​n​e​ ​w​h​o​ ​i​s​ ​g​r​i​e​v​i​n​g​.
	 */
	outro: string
	/**
	 * T​h​e​ ​p​l​u​g​-​i​n​ ​s​e​r​v​i​c​e​ ​i​s​ ​a​c​t​i​v​a​t​e​d​ ​o​n​ ​s​o​c​i​a​l​ ​m​e​d​i​a​ ​b​y​ ​t​h​o​s​e​ ​w​h​o​ ​h​a​v​e​ ​l​o​s​t​ ​s​o​m​e​o​n​e​ ​t​o​ ​i​n​d​i​c​a​t​e​ ​t​o​ ​o​t​h​e​r​s​ ​t​h​a​t​ ​t​h​e​ ​p​e​r​s​o​n​ ​i​s​ ​g​r​i​e​v​i​n​g​.
	 */
	outro1: string
	/**
	 * W​h​e​n​ ​y​o​u​ ​h​e​s​i​t​a​t​e​,​ ​r​a​n​d​o​m​ ​w​o​r​d​s​ ​a​r​e​ ​p​r​e​s​e​n​t​e​d​ ​t​o​ ​y​o​u​.​ ​I​f​ ​y​o​u​ ​d​e​l​e​t​e​ ​t​h​e​m​,​ ​n​o​t​h​i​n​g​ ​h​a​p​p​e​n​s​.​ ​Y​o​u​r​ ​m​e​s​s​a​g​e​ ​w​i​l​l​ ​b​e​ ​s​e​n​t​ ​r​e​g​a​r​d​l​e​s​s​ ​o​f​ ​h​o​w​ ​i​t​ ​e​n​d​s​ ​u​p​ ​-​ ​b​e​c​a​u​s​e​ ​i​t​'​s​ ​t​h​e​ ​t​h​o​u​g​h​t​ ​t​h​a​t​ ​c​o​u​n​t​s​.
	 */
	outro2: string
}

export type TranslationFunctions = {
	/**
	 * Write the name of a person you value:
	 */
	nameOfFriend: () => LocalizedString
	/**
	 * (not lover or best friend)
	 */
	nameOfFriend2: () => LocalizedString
	/**
	 * {person} has recently lost one of their loved ones.
	 */
	buildUp: (arg: { person: unknown }) => LocalizedString
	/**
	 * To make it less intimidating for you to show care, {person} has activated the service honest.txt.
	 */
	buildUp2: (arg: { person: unknown }) => LocalizedString
	/**
	 * Continue
	 */
	continueFromInfo: () => LocalizedString
	/**
	 * It's the thought that counts
	 */
	thoughtThatCounts: () => LocalizedString
	/**
	 * About
	 */
	about: () => LocalizedString
	/**
	 * Try again
	 */
	tryAgain: () => LocalizedString
	/**
	 * "honest.txt" is a threshold reducer, a cultural service for those of us who feel a bit awkward showing care for someone who is grieving.
	 */
	outro: () => LocalizedString
	/**
	 * The plug-in service is activated on social media by those who have lost someone to indicate to others that the person is grieving.
	 */
	outro1: () => LocalizedString
	/**
	 * When you hesitate, random words are presented to you. If you delete them, nothing happens. Your message will be sent regardless of how it ends up - because it's the thought that counts.
	 */
	outro2: () => LocalizedString
}

export type Formatters = {}
